class KMLConstants:
    POINT = "Point"
    LINESTRING = "LineString"
    POLYGON = "Polygon"
    PLACEMARK = "Placemark"
    NAME = "name"
    COORDINATES = "coordinates"
    DESCRIPTION = "description"
    OUTERBOUNDARYIS = "outerBoundaryIs"
    LINEARRING = "LinearRing"
